name: CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ruby
        run: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.0

      - name: Run tests
        run: bundle exec rake
