name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.5
          - 3.4

    steps:
      - uses: actions/checkout@v3

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
