name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run weekly
    - cron: "0 0 * * 0"

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      min_version: 3.1

  test:
    needs:
      - ruby-versions
    name: Test on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}

    steps:
      - uses: actions/checkout@v5

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake spec

  lint:
    needs:
      - ruby-versions
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.ruby-versions.outputs.latest }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake rubocop

  all-tests:
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: check test jobs
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
